### PR TITLE
FIX: Fix compilation error due to DirectionType redifinition

### PR DESCRIPTION
**Pull request by MichaelColonel**
Linux: https://slicer.cdash.org/build/2828610
Windows: https://slicer.cdash.org/build/2828808
Mac: https://slicer.cdash.org/build/2828797

### CODE REVIEW

**Comment by Sunderlandkyl** [comment]
Thanks!

**Comment by gregsharp** [comment]
Thanks Michael.  Is there an easy way for me to merge this into the gitlab repo?

**Comment by MichaelColonel** [comment]
I will make a PR into gitlab repository.

**Comment by MichaelColonel** [comment]
@gregsharp 

[Merge request](https://gitlab.com/plastimatch/plastimatch/-/merge_requests/31) in gitlab

**Comment by gregsharp** [comment]
Unfortunately this breaks CUDA.  I will work on an alternate solution.

**Comment by gregsharp** [comment]
Apparently I cannot re-open an issue that I didn't create.  But please consider it to be re-opened.

**Comment by MichaelColonel** [comment]
I can't re-open it, but i can create a new pull request to revert these changes.

**Comment by gregsharp** [comment]
I have a new fix for this in 753f6adb and eeb0884f.  Can you check if this will work?

How can I easily make a pull request from gitlab?

**Comment by gregsharp** [comment]
I think there is no need to revert, I merged yours, this will update from there.

**Comment by MichaelColonel** [comment]
I've checked gitlab updates, and both SlicerRT and Plastimatch were compiled successfully.
Tests are OK too.

**Comment by MichaelColonel** [comment]
Update: I've only tested in Linux, and i don't have CUDA.

**Comment by MichaelColonel** [comment]
> How can I easily make a pull request from gitlab?

I've cherry picked these two cuda commits, and i will try to create a pull request, and eventually update SlicerRT Plastimatch cmake file.

**Comment by MichaelColonel** [comment]
@gregsharp Could you check that #3 is OK, and my cherry picking is correct?

**Pull request merged**
